### ISSUE TITLE
Fix broken contact us page: "Sendgrid email failed to send"

### ISSUE THREAD

**Issue by aidengibbs** [GTBitsOfGood/hope-sustains-life#178]
Hope Sustains Life website  "Contact Us" page is broken. This ticket will require investigation into why this error is occurring and what we can do to fix the issue. 

![Image](https://user-images.githubusercontent.com/90468290/197357710-66e2db3f-256c-4cf5-b817-46c6ae8d3891.png)

**Comment by its-edmund** [comment]
Going ahead and closing this out, now that it's fixed on the development environment.
