### ISSUE TITLE
Our Work Page

### ISSUE THREAD

**Issue by shopaniuk** [GTBitsOfGood/hope-sustains-life#98]
We forgot to assign the Our Work page somehow lmao

**Comment by jlatour3** [comment]
Also, optimize for mobile.

**Comment by shopaniuk** [comment]
The Desktop view is done. Minor changes to the icons are needed

**Comment by jlatour3** [comment]
![image](https://user-images.githubusercontent.com/46651129/101846786-af89ca00-3b1f-11eb-9b86-24abc96ee087.png)
LOL where's the icon's heads?

**Comment by shopaniuk** [comment]
LMAO. That’s how I got them from the Figma! If you can get me the icons as wholes then I can add them in easily!

**Comment by shopaniuk** [comment]
Icons fixed!
